// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gioyluxjweuicdlcknyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpb3lsdXhqd2V1aWNkbGNrbnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzc3NjcsImV4cCI6MjA1ODkxMzc2N30.dl5U8K6cyZ5k8QvhGHZ-DRFlVUHAIA5j61iwpWaKI0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);